### ISSUE TITLE
Tree shaking在webpack4下unused harmony

### ISSUE THREAD

**Issue by sally2015** [easonyq/easonyq.github.io#1]
webpack4.16.5
mode=development
打包出来的bundle.js并没有unused harmony这句注释。虽然官方文档还是这么写，是不是通过了另外的方式检测未使用的模块

**Comment by easonyq** [comment]
没错，webpack4 和 3 相比，在这里有一个细微的改变，即 `mode = development` 时，__不再进行__ 是否被使用的检测，统一认为被使用了，这是为了加快开发状态下的编译速度，给开发带来良好的体验。

在 webpack4 中，如果你也想看到和 webpack3 一样的 `unused harmony export` 的话，你可以使用以下 webpack.config.js：

```javascript
module.exports = {
  entry: 'xxx',
  output: {xxx},
  mode: 'production',
  // mode: 'development',
  optimization: {
    minimize: false,
    concatenateModules: false
  },
  devtool: false
}
```
